import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/nav-bar";

// Fonts
const sebangGothic = localFont({
  src: [
    {
      path: "./SEBANG Gothic OTF.otf",
      style: "normal",
      weight: "400",
    },
    {
      path: "./SEBANG Gothic OTF Bold.otf",
      style: "bold",
      weight: "700",
    },
  ],
});

// MetaData
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sebangGothic.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
